name: NPM Publish
on:
    push:
        branches:
            - master
jobs:
    npm-publish:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@master
            - name: Install
              uses: Borales/actions-yarn@v2.0.1
              with:
                  cmd: install
            - name: Build
              uses: Borales/actions-yarn@v2.0.1
              with:
                  cmd: build
            - name: Publish
              uses: Borales/actions-yarn@v2.0.1
              env:
                  NPM_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
              with:
                  cmd: publish --access public
            - uses: butlerlogic/action-autotag@stable
              with:
                  GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}
                  tag_prefx: 'v'
