name: Build and Deploy Documentation
on:
    push:
        branches:
            - master
jobs:
    build-and-deploy-documentation:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@master
            - name: Build and Deploy
              uses: JamesIves/github-pages-deploy-action@master
              env:
                  ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
                  BASE_BRANCH: master
                  BRANCH: gh-pages
                  FOLDER: storybook-public
                  # build-storybook: "build-storybook -c .storybook -o storybook-public"
                  BUILD_SCRIPT: npm install && npm run build-storybook
