name: Build and Deploy Storybook
on:
    push:
        branches:
            - master
jobs:
    build-and-deploy-documentation:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@master
            - name: Install
              uses: Borales/actions-yarn@v2.0.1
              with:
                  cmd: install
            - name: Build
              uses: Borales/actions-yarn@v2.0.1
              with:
                  cmd: build-storybook
            - name: Display Workspace
              run: ls -la
              shell: bash
            - name: Deploy
              uses: peaceiris/actions-gh-pages@v2.5.0
              env:
                  PERSONAL_TOKEN: ${{ secrets.ACCESS_TOKEN }}
                  PUBLISH_BRANCH: gh-pages
                  PUBLISH_DIR: ./storybook-static
