name: Build and Deploy Storybook
on:
    push:
        branches:
            - master
jobs:
    build-and-deploy-documentation:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@master
            - name: Install
              uses: Borales/actions-yarn@master
              with:
                  args: install
            - name: Build
              uses: Borales/actions-yarn@master
              with:
                  args: build-storybook
            - name: Deploy
              uses: JamesIves/github-pages-deploy-action@master
              env:
                  ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
                  BASE_BRANCH: master
                  BRANCH: gh-pages
                  FOLDER: storybook-static
